name: terraform-registry

channels:
  - conda-forge

dependencies:
  # Development Dependencies
  - chalice 1.12
  - click >=6,<8
  - docker-py
  - ipython
  - liquidprompt
  - python 3.7
  - pre-commit

  # Runtime Dependencies (must match requirements.txt)
  - environs
  - jinja2
  - pynamodb
  - python-dateutil
  - requests
  - semver

  # Test Dependencies
  - coverage
  - pytest
  - pytest-chalice
  - terraform
