name: terraform-registry

channels:
  - conda-forge

dependencies:
  - python 3.7
  - ipython
  - liquidprompt
  - pre-commit

  - chalice
  - pynamodb

  - pytest
  - pytest-chalice

  # - ngrok, open an account at ngrok.com
