name: terraform-registry

channels:
  - conda-forge

dependencies:
  # Development Dependencies
  - chalice 1.12
  - click >=6,<8
  - ipython
  - liquidprompt
  - python 3.7
  - pre-commit
  # - ngrok, open an account at ngrok.com

  # Runtime Dependencies (must match requirements.txt)
  - environs
  - pynamodb
  - semver

  # Test Dependencies
  - coverage
  - pytest
  - pytest-chalice
